### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by tim6her** [noelmarkham/learn-you-a-haskell-exercises#7]
Dear Noel,

thanks for compiling these exercises! They are of great help to me learning Haskell.

However, you did not provide a license with your code. Is it alright for you if I fork the repo and push solutions to my fork? I do not whish do imply in any way that I created the exercises.

If you want me to add a clarifying line in the README, please let me know.

Best regards,

Tim

**Comment by noelmarkham** [comment]
Hi Tim,

Thank you very much for raising the issue, and something I should have dealt with at the time. I've updated the repo to include a license, GPL3.

Thanks
Noel

**Comment by tim6her** [comment]
Hi Noel,

Thanks, I've pulled your changes. Now I don't need to have a bad conscience any more. 😉 

- Tim
